package com.hnam.week5demo

const val ACCOUNT_NAME_KEY = "ACCOUNT_NAME_KEY"
const val ACCOUNT_DESCRIPTION_KEY = "ACCOUNT_CLUB_KEY"
const val ACCOUNT_AVATAR_KEY = "ACCOUNT_AVATAR_KEY"
const val ACCOUNT_OBJECT_KEY = "ACCOUNT_OBJECT_KEY"
const val DATABASE_NAME = "KHTN-APP.db"
const val CODE_ADD_NEW_ACCOUNT = 12
const val CODE_ADD_UPDATE_ACCOUNT = 13